apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.cyphix.ble'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace 'com.cyphix.ble'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  lintOptions {
    abortOnError false
  }
}
